import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

const projectRoot = path.resolve(import.meta.dirname, "..");
const dataDir = path.join(projectRoot, "public", "data");
const healthcareDir = path.join(dataDir, "healthcare");
const facilitiesPath = path.join(healthcareDir, "facilities.json");
const statesPath = path.join(dataDir, "us-states.geojson");
const countiesDir = path.join(dataDir, "counties", "by-state");
const localJurisdictionsDir = path.join(dataDir, "cousubs", "by-state");
const outputPath = path.join(healthcareDir, "facility-boundary-assignments.json");

const supportedGeographyBounds = {
  minLatitude: 24,
  maxLatitude: 50,
  minLongitude: -125,
  maxLongitude: -66
};

const boundaryDataVersion =
  "Census 2024 cartographic legal/admin boundary GeoJSON generated by scripts/download-boundaries.mjs";

function parseArgs(argv) {
  const args = {
    write: false,
    outputPath
  };

  for (const arg of argv) {
    if (arg === "--write") {
      args.write = true;
    } else if (arg === "--help" || arg === "-h") {
      args.help = true;
    } else if (arg.startsWith("--output=")) {
      args.outputPath = path.resolve(projectRoot, arg.slice("--output=".length));
    } else {
      throw new Error(`Unknown option "${arg}".`);
    }
  }

  return args;
}

function printHelp() {
  console.log("Assign production healthcare facilities to official boundaries.");
  console.log("");
  console.log("Usage:");
  console.log("  npm run assign:facility-boundaries");
  console.log("  npm run assign:facility-boundaries -- --write");
  console.log("  node scripts/assignFacilityBoundaries.mjs --output=public/data/healthcare/facility-boundary-assignments.json --write");
  console.log("");
  console.log("Without --write, the script prints a dry-run report and does not write the assignment artifact.");
}

function relativePath(filePath) {
  return path.relative(projectRoot, filePath).replaceAll(path.sep, "/");
}

async function readJson(filePath) {
  return JSON.parse(await fs.readFile(filePath, "utf8"));
}

async function readJsonWithChecksum(filePath) {
  const raw = await fs.readFile(filePath, "utf8");

  return {
    data: JSON.parse(raw),
    checksum: createHash("sha256").update(raw).digest("hex")
  };
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function getPropertyText(feature, propertyNames) {
  if (!isObject(feature?.properties)) {
    return null;
  }

  for (const propertyName of propertyNames) {
    const value = feature.properties[propertyName];

    if ((typeof value === "string" && value.trim()) || typeof value === "number") {
      return String(value).trim();
    }
  }

  return null;
}

function getFeatureName(feature) {
  return getPropertyText(feature, ["NAMELSAD", "NAME", "STATE_NAME"]);
}

function getLocalJurisdictionType(feature) {
  const namelsad = getPropertyText(feature, ["NAMELSAD"]);
  const name = getPropertyText(feature, ["NAME"]);

  if (!namelsad || !name || namelsad === name) {
    return null;
  }

  return namelsad.slice(name.length).trim() || null;
}

function isFeatureCollection(data) {
  return (
    isObject(data) &&
    data.type === "FeatureCollection" &&
    Array.isArray(data.features)
  );
}

function isBoundaryFeature(feature) {
  return (
    isObject(feature) &&
    feature.type === "Feature" &&
    isObject(feature.geometry) &&
    (feature.geometry.type === "Polygon" || feature.geometry.type === "MultiPolygon")
  );
}

function validateBoundaryData(data, label) {
  if (!isFeatureCollection(data)) {
    throw new Error(`${label} must be a GeoJSON FeatureCollection.`);
  }

  if (data.features.some((feature) => !isBoundaryFeature(feature))) {
    throw new Error(`${label} must contain only Polygon or MultiPolygon boundary features.`);
  }
}

function getFeatureCoordinates(feature) {
  if (feature.geometry.type === "Polygon") {
    return feature.geometry.coordinates.flat(1);
  }

  return feature.geometry.coordinates.flat(2);
}

function getFeatureBounds(feature) {
  const coordinates = getFeatureCoordinates(feature);
  let minLongitude = Infinity;
  let maxLongitude = -Infinity;
  let minLatitude = Infinity;
  let maxLatitude = -Infinity;

  for (const [longitude, latitude] of coordinates) {
    minLongitude = Math.min(minLongitude, longitude);
    maxLongitude = Math.max(maxLongitude, longitude);
    minLatitude = Math.min(minLatitude, latitude);
    maxLatitude = Math.max(maxLatitude, latitude);
  }

  return { minLatitude, maxLatitude, minLongitude, maxLongitude };
}

function prepareFeatures(features) {
  return features.map((feature) => ({
    feature,
    bounds: getFeatureBounds(feature)
  }));
}

function isPointInBounds(latitude, longitude, bounds) {
  return (
    latitude >= bounds.minLatitude &&
    latitude <= bounds.maxLatitude &&
    longitude >= bounds.minLongitude &&
    longitude <= bounds.maxLongitude
  );
}

function isPointInRing(latitude, longitude, ring) {
  let isInside = false;

  for (
    let index = 0, previousIndex = ring.length - 1;
    index < ring.length;
    previousIndex = index++
  ) {
    const [currentLongitude, currentLatitude] = ring[index];
    const [previousLongitude, previousLatitude] = ring[previousIndex];
    const crossesLatitude =
      currentLatitude > latitude !== previousLatitude > latitude;
    const crossingLongitude =
      ((previousLongitude - currentLongitude) * (latitude - currentLatitude)) /
        (previousLatitude - currentLatitude) +
      currentLongitude;

    if (crossesLatitude && longitude < crossingLongitude) {
      isInside = !isInside;
    }
  }

  return isInside;
}

function isPointInPolygon(latitude, longitude, polygon) {
  const outerRing = polygon[0];

  if (!outerRing || !isPointInRing(latitude, longitude, outerRing)) {
    return false;
  }

  return polygon.slice(1).every((hole) => !isPointInRing(latitude, longitude, hole));
}

function isPointInFeature(latitude, longitude, feature) {
  if (feature.geometry.type === "Polygon") {
    return isPointInPolygon(latitude, longitude, feature.geometry.coordinates);
  }

  return feature.geometry.coordinates.some((polygon) =>
    isPointInPolygon(latitude, longitude, polygon)
  );
}

function findContainingFeature(preparedFeatures, latitude, longitude) {
  return (
    preparedFeatures.find(
      ({ feature, bounds }) =>
        isPointInBounds(latitude, longitude, bounds) &&
        isPointInFeature(latitude, longitude, feature)
    )?.feature ?? null
  );
}

// A coordinate near a shared edge can fall inside overlapping simplified
// polygons from neighboring counties, so prefer the containing local
// jurisdiction that agrees with the already-assigned county.
function findContainingLocalFeature(preparedFeatures, latitude, longitude, countyFips) {
  const containingFeatures = preparedFeatures
    .filter(
      ({ feature, bounds }) =>
        isPointInBounds(latitude, longitude, bounds) &&
        isPointInFeature(latitude, longitude, feature)
    )
    .map(({ feature }) => feature);

  if (containingFeatures.length === 0) {
    return null;
  }

  if (!countyFips) {
    return containingFeatures[0];
  }

  // When the only containing local polygon disagrees with the assigned
  // county (a simplification artifact at shared edges), leave the local
  // level unassigned instead of recording a contradictory boundary.
  return (
    containingFeatures.find(
      (feature) =>
        getPropertyText(feature, ["COUNTYFP", "COUNTYFP20"]).padStart(3, "0") ===
        countyFips
    ) ?? null
  );
}

function hasValidCoordinateRange(latitude, longitude) {
  return (
    typeof latitude === "number" &&
    Number.isFinite(latitude) &&
    latitude >= -90 &&
    latitude <= 90 &&
    typeof longitude === "number" &&
    Number.isFinite(longitude) &&
    longitude >= -180 &&
    longitude <= 180
  );
}

function isInsideSupportedGeographyBounds(latitude, longitude) {
  return isPointInBounds(latitude, longitude, supportedGeographyBounds);
}

function createEmptyBoundaryStatus(status) {
  return {
    status,
    geoid: null,
    name: null
  };
}

function createStateAssignment(feature) {
  const geoid = getPropertyText(feature, ["GEOID", "GEOID20", "GEOID10"]);
  const stateFips = getPropertyText(feature, ["STATEFP", "STATEFP20"]) ?? geoid;
  const name = getPropertyText(feature, ["NAME", "STATE_NAME"]);

  if (!geoid || !stateFips || !name) {
    return null;
  }

  return {
    status: "assigned",
    geoid,
    stateFips: stateFips.padStart(2, "0"),
    name
  };
}

function createCountyAssignment(feature) {
  const geoid = getPropertyText(feature, ["GEOID", "GEOID20", "GEOID10"]);
  const stateFips = getPropertyText(feature, ["STATEFP", "STATEFP20"]);
  const countyFips = getPropertyText(feature, ["COUNTYFP", "COUNTYFP20"]);
  const name = getFeatureName(feature);

  if (!geoid || !stateFips || !countyFips || !name) {
    return null;
  }

  return {
    status: "assigned",
    geoid,
    stateFips: stateFips.padStart(2, "0"),
    countyFips: countyFips.padStart(3, "0"),
    name
  };
}

function createLocalJurisdictionAssignment(feature) {
  const geoid = getPropertyText(feature, ["GEOID", "GEOID20", "GEOID10"]);
  const stateFips = getPropertyText(feature, ["STATEFP", "STATEFP20"]);
  const countyFips = getPropertyText(feature, ["COUNTYFP", "COUNTYFP20"]);
  const cousubFips = getPropertyText(feature, ["COUSUBFP", "COUSUBFP20"]);
  const name = getFeatureName(feature);

  if (!geoid || !stateFips || !countyFips || !cousubFips || !name) {
    return null;
  }

  return {
    status: "assigned",
    geoid,
    stateFips: stateFips.padStart(2, "0"),
    countyFips: countyFips.padStart(3, "0"),
    cousubFips: cousubFips.padStart(5, "0"),
    name,
    type: getLocalJurisdictionType(feature)
  };
}

async function loadBoundaryCache(stateFips, cache, dir, label) {
  if (cache.has(stateFips)) {
    return cache.get(stateFips);
  }

  const filePath = path.join(dir, `${stateFips}.geojson`);

  if (!(await fileExists(filePath))) {
    cache.set(stateFips, null);
    return null;
  }

  const data = await readJson(filePath);
  validateBoundaryData(data, `${label} ${stateFips}`);
  const entry = {
    filePath,
    features: prepareFeatures(data.features)
  };

  cache.set(stateFips, entry);
  return entry;
}

function buildBaseAssignment(facility) {
  return {
    facilityId: typeof facility.id === "string" ? facility.id : "",
    facilityName: typeof facility.name === "string" ? facility.name : "",
    coordinate: null,
    status: "no_matching_boundary",
    state: createEmptyBoundaryStatus("not_attempted"),
    county: createEmptyBoundaryStatus("not_attempted"),
    localJurisdiction: createEmptyBoundaryStatus("not_attempted"),
    warnings: []
  };
}

async function assignFacility(facility, boundaryContext) {
  const assignment = buildBaseAssignment(facility);
  const latitude = facility.latitude;
  const longitude = facility.longitude;

  if (latitude === undefined || latitude === null || longitude === undefined || longitude === null) {
    assignment.status = "missing_coordinates";
    assignment.state.status = "not_attempted";
    assignment.county.status = "not_attempted";
    assignment.localJurisdiction.status = "not_attempted";
    assignment.warnings.push("Facility is missing latitude or longitude and was not assigned.");
    return assignment;
  }

  if (!hasValidCoordinateRange(latitude, longitude)) {
    assignment.status = "invalid_coordinates";
    assignment.warnings.push("Facility coordinates are invalid and were not assigned.");
    return assignment;
  }

  assignment.coordinate = {
    latitude,
    longitude
  };

  if (!isInsideSupportedGeographyBounds(latitude, longitude)) {
    assignment.status = "outside_supported_geography";
    assignment.warnings.push("Facility coordinates are outside the supported lower 48 plus Washington, D.C. bounds.");
    return assignment;
  }

  const stateFeature = findContainingFeature(
    boundaryContext.states.features,
    latitude,
    longitude
  );

  if (!stateFeature) {
    assignment.status = "no_matching_boundary";
    assignment.state.status = "no_matching_boundary";
    assignment.county.status = "not_attempted";
    assignment.localJurisdiction.status = "not_attempted";
    assignment.warnings.push("No supported official state boundary contains the facility coordinate.");
    return assignment;
  }

  const stateAssignment = createStateAssignment(stateFeature);

  if (!stateAssignment) {
    assignment.status = "partial_assignment";
    assignment.state.status = "missing_official_id";
    assignment.warnings.push("Matched state boundary is missing a stable official identifier.");
    return assignment;
  }

  assignment.state = stateAssignment;

  const countyEntry = await loadBoundaryCache(
    stateAssignment.stateFips,
    boundaryContext.countiesByState,
    countiesDir,
    "county boundaries"
  );

  if (!countyEntry) {
    assignment.county.status = "boundary_unavailable";
    assignment.localJurisdiction.status = "not_attempted";
    assignment.status = "partial_assignment";
    assignment.warnings.push(`County boundary file is unavailable for state FIPS ${stateAssignment.stateFips}.`);
    return assignment;
  }

  const countyFeature = findContainingFeature(countyEntry.features, latitude, longitude);

  if (!countyFeature) {
    assignment.county.status = "no_matching_boundary";
    assignment.localJurisdiction.status = "not_attempted";
    assignment.status = "partial_assignment";
    assignment.warnings.push("No supported official county boundary contains the facility coordinate.");
    return assignment;
  }

  const countyAssignment = createCountyAssignment(countyFeature);

  if (!countyAssignment) {
    assignment.county.status = "missing_official_id";
    assignment.localJurisdiction.status = "not_attempted";
    assignment.status = "partial_assignment";
    assignment.warnings.push("Matched county boundary is missing a stable official identifier.");
    return assignment;
  }

  assignment.county = countyAssignment;

  const localEntry = await loadBoundaryCache(
    stateAssignment.stateFips,
    boundaryContext.localJurisdictionsByState,
    localJurisdictionsDir,
    "local jurisdiction boundaries"
  );

  if (!localEntry) {
    assignment.localJurisdiction.status = "local_boundary_unavailable";
    assignment.status = "partial_assignment";
    assignment.warnings.push(`Local jurisdiction boundary file is unavailable for state FIPS ${stateAssignment.stateFips}.`);
    return assignment;
  }

  const localFeature = findContainingLocalFeature(
    localEntry.features,
    latitude,
    longitude,
    countyAssignment.countyFips
  );

  if (!localFeature) {
    assignment.localJurisdiction.status = "local_boundary_not_matched";
    assignment.status = "partial_assignment";
    assignment.warnings.push("No supported official local jurisdiction boundary contains the facility coordinate.");
    return assignment;
  }

  const localAssignment = createLocalJurisdictionAssignment(localFeature);

  if (!localAssignment) {
    assignment.localJurisdiction.status = "missing_official_id";
    assignment.status = "partial_assignment";
    assignment.warnings.push("Matched local jurisdiction boundary is missing a stable official identifier.");
    return assignment;
  }

  assignment.localJurisdiction = localAssignment;
  assignment.status = "assigned";
  return assignment;
}

function summarizeAssignments(assignments) {
  const statusCounts = assignments.reduce((counts, assignment) => {
    counts[assignment.status] = (counts[assignment.status] ?? 0) + 1;
    return counts;
  }, {});

  return {
    totalFacilities: assignments.length,
    assigned: statusCounts.assigned ?? 0,
    partialAssignment: statusCounts.partial_assignment ?? 0,
    missingCoordinates: statusCounts.missing_coordinates ?? 0,
    invalidCoordinates: statusCounts.invalid_coordinates ?? 0,
    outsideSupportedGeography: statusCounts.outside_supported_geography ?? 0,
    noMatchingBoundary: statusCounts.no_matching_boundary ?? 0,
    statusCounts
  };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    return;
  }

  const { data: facilities, checksum: facilitiesChecksum } =
    await readJsonWithChecksum(facilitiesPath);
  const { data: states, checksum: statesChecksum } = await readJsonWithChecksum(statesPath);

  if (!Array.isArray(facilities)) {
    throw new Error(`${relativePath(facilitiesPath)} must contain a JSON array.`);
  }

  validateBoundaryData(states, "state boundaries");

  const boundaryContext = {
    states: {
      filePath: statesPath,
      features: prepareFeatures(states.features)
    },
    countiesByState: new Map(),
    localJurisdictionsByState: new Map()
  };

  const assignments = [];
  const generatedAt = new Date().toISOString();

  for (const facility of facilities) {
    const assignment = await assignFacility(facility, boundaryContext);
    assignment.assignedAt = generatedAt;
    assignment.sourceFacilityVersion =
      facility.sourceLastUpdated ?? facility.importDate ?? facility.lastVerified ?? null;
    assignments.push(assignment);
  }

  const assignmentArtifact = {
    metadata: {
      generatedAt,
      assignmentMethod: "coordinate_point_in_official_polygon",
      boundaryDataVersion,
      supportedGeography: "Lower 48 U.S. states plus Washington, D.C.",
      inputFiles: {
        facilities: relativePath(facilitiesPath),
        states: relativePath(statesPath),
        countiesByState: relativePath(countiesDir),
        localJurisdictionsByState: relativePath(localJurisdictionsDir)
      },
      inputChecksums: {
        facilities: facilitiesChecksum,
        states: statesChecksum
      },
      summary: summarizeAssignments(assignments)
    },
    assignments
  };

  console.log("Facility boundary assignment report");
  console.log(`Facilities: ${assignments.length}`);
  console.log(`Assigned: ${assignmentArtifact.metadata.summary.assigned}`);
  console.log(`Partial assignment: ${assignmentArtifact.metadata.summary.partialAssignment}`);
  console.log(`Missing coordinates: ${assignmentArtifact.metadata.summary.missingCoordinates}`);
  console.log(`Invalid coordinates: ${assignmentArtifact.metadata.summary.invalidCoordinates}`);
  console.log(`Outside supported geography: ${assignmentArtifact.metadata.summary.outsideSupportedGeography}`);
  console.log(`No matching boundary: ${assignmentArtifact.metadata.summary.noMatchingBoundary}`);

  if (!args.write) {
    console.log("Dry run only. Use --write to update the assignment artifact.");
    return;
  }

  await fs.writeFile(
    args.outputPath,
    `${JSON.stringify(assignmentArtifact, null, 2)}\n`,
    "utf8"
  );
  console.log(`Wrote ${relativePath(args.outputPath)}.`);
}

main().catch((error) => {
  console.error("Facility boundary assignment failed.");
  console.error(error.message);
  process.exit(1);
});
